# Require the Pod executable and execute a command using Node.js to resolve the path to react_native_pods.rb
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]).strip

# Specify the platform and prepare the React Native project
platform :ios, min_ios_version_supported
prepare_react_native_project!

# Determine whether to use frameworks and configure accordingly
linkage = ENV['USE_FRAMEWORKS']
if linkage
  puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks linkage: linkage.to_sym
else
  use_frameworks!
end

# Configure the target and its dependencies
target 'TestAwsPinpoint' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    app_path: "#{Pod::Config.instance.installation_root}/.."
  )

  # Configure the test target
  target 'TestAwsPinpointTests' do
    inherit :complete
    # Pods specifically for testing
  end

  # Post-install hook for additional configuration
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false
      # ccache_enabled: true uncomment if needed
    )
  end
end
